export const HE = {
  app: {
    title: '4MP — ניהול מכירות',
    subtitle: 'מערכת ניהול מכירות',
  },

  nav: {
    dashboard: 'דשבורד',
    crm: 'CRM',
    leads: 'לידים',
    meetings: 'פגישות',
    sales: 'מכירות',
    customers: 'לקוחות',
    machines: 'מכונות',
    installations: 'התקנות',
    training: 'הדרכות',
    reports: 'דוחות',
    users: 'משתמשים',
    settings: 'הגדרות',
    salesSection: 'מכירות',
    manageSection: 'ניהול',
  },

  common: {
    save: 'שמירה',
    cancel: 'ביטול',
    search: 'חיפוש',
    edit: 'עריכה',
    delete: 'מחיקה',
    add: 'הוספה',
    back: 'חזרה',
    noData: 'אין נתונים להצגה',
    loading: 'טוען...',
    close: 'סגירה',
    email: 'דוא"ל',
    phone: 'טלפון',
    name: 'שם',
    city: 'עיר',
    address: 'כתובת',
    status: 'סטטוס',
    date: 'תאריך',
    time: 'שעה',
    notes: 'הערות',
    all: 'הכל',
    actions: 'פעולות',
    active: 'פעיל',
    inactive: 'לא פעיל',
    confirm: 'אישור',
    yes: 'כן',
    no: 'לא',
    total: 'סה"כ',
    createdAt: 'נוצר בתאריך',
    optional: 'אופציונלי',
    required: 'שדה חובה',
    logout: 'התנתקות',
    menu: 'תפריט',
    viewAsRole: 'הצג כתפקיד',
    backToAdmin: 'חזרה לתצוגת מנהל',
    page: 'עמוד',
    of: 'מתוך',
    previous: 'הקודם',
    next: 'הבא',
    new: 'חדש',
  },

  auth: {
    loginTitle: 'התחברות למערכת',
    email: 'דוא"ל',
    password: 'סיסמה',
    loginButton: 'התחברות',
    loginError: 'דוא"ל או סיסמה שגויים',
    loggingIn: 'מתחבר...',
  },

  leadSource: {
    facebook: 'פייסבוק',
    instagram: 'אינסטגרם',
    google_paid: 'גוגל ממומן',
    google_organic: 'גוגל אורגני',
    tiktok: 'טיקטוק',
    youtube: 'יוטיוב',
    whatsapp: 'וואטסאפ',
    direct: 'ישיר',
    friend: 'הפניה מחבר',
    website: 'אתר',
    phone: 'טלפון',
  },

  leadStatus: {
    new: 'חדש',
    contacted: 'יצרנו קשר',
    meeting: 'פגישה',
    in_progress: 'בתהליך',
    interested: 'מעוניין',
    proposal: 'הצעה',
    won: 'נסגר',
    lost: 'הפסד',
    not_relevant: 'לא רלוונטי',
    double: 'כפול',
    service_existing: 'שירות ללקוח קיים',
    clinical_inquiry: 'פנייה קלינית',
  },

  businessType: {
    cosmetician: 'קוסמטיקאית',
    doctor: 'רופא/ה',
    clinic: 'קליניקה',
  },

  crm: {
    title: 'CRM',
    pipelineTitle: 'צינור מכירות',
    addLead: 'הוספת ליד',
    filterBySalesperson: 'סינון לפי איש מכירות',
  },

  leads: {
    title: 'לידים',
    addLead: 'הוספת ליד',
    editLead: 'עריכת ליד',
    searchPlaceholder: 'חיפוש לפי שם או טלפון',
    filterStatus: 'סינון לפי סטטוס',
    filterSource: 'סינון לפי מקור',
    filterAssigned: 'סינון לפי איש מכירות',
    showArchived: 'הצג ארכיון',
    archived: 'בארכיון',
    duplicatePhoneTitle: 'מספר טלפון קיים במערכת',
    duplicatePhoneText: 'קיים ליד עם מספר טלפון זהה. האם לסמן ליד זה כליד חוזר?',
    markAsReturning: 'סמן כליד חוזר',
    customerDetails: 'פרטי לקוח',
    createAnyway: 'צור בכל זאת',
    score: 'ציון ליד',
    source: 'מקור',
    clientStatus: 'סטטוס לקוח',
    clientExisting: 'לקוח קיים',
    clientNew: 'לקוח חדש',
    dealValue: 'ערך כספי (₪)',
    assignedTo: 'איש מכירות',
    machinesInterested: 'מכונות מעניינות',
    businessType: 'סוג עסק',
    followUpDate: 'תאריך מעקב',
    conversationSummary: 'סיכום שיחה',
    originUrl: 'מקור הפניה (URL)',
    oldSystemNotes: 'הערות ממערכת ישנה',
    interactions: 'אינטראקציות',
    addInteraction: 'הוספת אינטראקציה',
    interactionContent: 'תוכן',
    reminders: 'תזכורות',
    addReminder: 'הוספת תזכורת',
    reminderText: 'טקסט תזכורת',
    scheduleMeeting: 'קביעת פגישה',
    isReturn: 'ליד חוזר',
    interactionType: {
      note: 'הערה',
      call: 'שיחת טלפון',
      whatsapp: 'וואטסאפ',
      email: 'דוא"ל',
      log: 'יומן',
    },
  },

  meetings: {
    title: 'פגישות',
    addMeeting: 'הוספת פגישה',
    editMeeting: 'עריכת פגישה',
    meetingTitle: 'כותרת',
    customerName: 'שם לקוח/ליד',
    meetingType: 'סוג פגישה',
    location: 'מיקום',
    outcome: 'תוצאה',
    scheduledDate: 'תאריך מתוכנן',
    scheduledTime: 'שעה מתוכננת',
    linkLead: 'קישור לליד',
    linkCustomer: 'קישור ללקוח',
    salesperson: 'איש מכירות',
    noMeetings: 'אין פגישות להצגה',
    deleteMeeting: 'מחיקת פגישה',
    deleteMeetingConfirm: 'האם למחוק פגישה זו? הפעולה תמחק גם את הרישום התואם מהיסטוריית הליד.',
  },

  meetingType: {
    in_person: 'פגישה פרונטלית',
    video: 'שיחת וידאו',
    phone: 'שיחת טלפון',
  },

  meetingStatus: {
    scheduled: 'מתוכננת',
    completed: 'הושלמה',
    cancelled: 'בוטלה',
    no_show: 'לא הגיע',
  },

  machines: {
    title: 'מכונות',
    addMachine: 'הוספת מכונה',
    editMachine: 'עריכת מכונה',
    description: 'תיאור',
    price: 'מחיר',
    imageUrl: 'קישור לתמונה',
    variations: 'וריאציות',
    addVariation: 'הוספת וריאציה',
    variationName: 'שם וריאציה',
    priceModifier: 'תוספת מחיר',
    categories: 'קטגוריות',
    prices: 'מחירים',
    addPrice: 'הוספת מחיר',
    priceName: 'שם המחיר',
    priceAmount: 'סכום',
    adminOnlyPrices: 'רק מנהל יכול לערוך מחירים',
    noCategory: 'ללא קטגוריה',
  },

  settings: {
    title: 'הגדרות',
    machineCategories: 'קטגוריות מכונות',
    addCategory: 'הוספת קטגוריה',
    categoryName: 'שם קטגוריה',
    color: 'צבע',
    deleteCategoryConfirm: 'למחוק קטגוריה זו?',
    colorOptions: {
      blue: 'כחול',
      pink: 'ורוד',
      purple: 'סגול',
      amber: 'כתום',
      teal: 'טורקיז',
      green: 'ירוק',
      red: 'אדום',
      gray: 'אפור',
    },
  },

  customers: {
    title: 'לקוחות',
    addCustomer: 'הוספת לקוח',
    editCustomer: 'עריכת לקוח',
    contactName: 'איש קשר',
    machineCount: 'מס\' מכונות',
    customerType: 'סוג לקוח',
    salesHistory: 'היסטוריית מכירות',
    installationsHistory: 'היסטוריית התקנות',
    pickExisting: 'בחירת לקוח קיים',
    createNew: 'לקוח חדש',
    sharplightId: 'מס\' לקוח (Sharplight)',
    existingMachines: 'מכונה קיימת',
    machineIdNumber: 'מס\' מכשיר',
    machineShippedDate: 'תאריך משלוח',
  },

  sales: {
    title: 'מכירות',
    addSale: 'הוספת מכירה',
    editSale: 'עריכת מכירה',
    saleDetails: 'פרטי מכירה',
    customer: 'לקוח',
    machinesSection: 'מכונות',
    addMachineLine: 'הוספת מכונה',
    quantity: 'כמות',
    variation: 'וריאציה',
    serial: 'מספר סידורי',
    payments: 'תשלומים',
    addPayment: 'הוספת תשלום',
    paymentType: 'אמצעי תשלום',
    amount: 'סכום',
    invoiceLink: 'קישור לחשבונית',
    deliveryType: 'סוג אספקה',
    linkLead: 'קישור לליד',
    searchByPhone: 'חיפוש לפי טלפון',
    autoCreateInstallations: 'ליצור אוטומטית משימות התקנה עבור מכונות אלו?',
    paymentMismatch: 'סכום התשלומים חייב להיות שווה לסכום הכולל',
  },

  saleStatus: {
    new: 'חדש',
    confirmed: 'מאושר',
    paid: 'שולם',
    delivered: 'נשלח',
    installed: 'הותקן',
    cancelled: 'בוטל',
  },

  deliveryType: {
    pickup: 'איסוף עצמי',
    delivery: 'משלוח',
    delivery_and_install: 'משלוח + התקנה',
  },

  paymentType: {
    cash: 'מזומן',
    credit: 'אשראי',
    transfer: 'העברה בנקאית',
    check: "צ'ק",
  },

  installations: {
    title: 'התקנות',
    addInstallation: 'הוספת התקנה',
    editInstallation: 'עריכת התקנה',
    technician: 'טכנאי/ת',
    plannedDate: 'תאריך מתוכנן',
    actualDate: 'תאריך ביצוע בפועל',
    machine: 'מכונה',
    serialNumber: 'מספר סידורי',
    linkSale: 'קישור למכירה',
    markCompleted: 'סמן כהושלם',
    markCancelled: 'סמן כבוטל',
    noInstallations: 'אין התקנות להצגה',
  },

  installationStatus: {
    pending: 'ממתין',
    scheduled: 'מתוכנן',
    completed: 'הושלם',
    cancelled: 'בוטל',
  },

  training: {
    title: 'הדרכות',
    addSession: 'הוספת הדרכה',
    editSession: 'עריכת הדרכה',
    name: 'שם ההדרכה',
    description: 'תיאור',
    subject: 'נושא',
    startDate: 'תאריך התחלה',
    endDate: 'תאריך סיום',
    attendees: 'משתתפים',
    addAttendee: 'הוספת משתתף/ת',
    searchAttendee: 'חיפוש ליד/לקוח לפי שם או טלפון',
    noAttendees: 'אין משתתפים עדיין',
    noSessions: 'אין הדרכות להצגה',
    noResults: 'לא נמצאו תוצאות',
    lead: 'ליד',
    customer: 'לקוח',
    prevMonth: 'חודש קודם',
    nextMonth: 'חודש הבא',
  },

  dashboard: {
    title: 'דשבורד',
    newLeadsToday: 'לידים חדשים היום',
    meetingsThisWeek: 'פגישות השבוע',
    salesThisMonth: 'מכירות החודש',
    pendingInstallations: 'התקנות ממתינות',
  },

  reports: {
    title: 'דוחות',
    noPermission: 'אין לך הרשאה לצפות בדוחות',
    dateRange: 'טווח תאריכים',
    thisWeek: 'השבוע',
    last30Days: '30 ימים אחרונים',
    monthToDate: 'החודש הנוכחי',
    custom: 'טווח מותאם',
    from: 'מתאריך',
    to: 'עד תאריך',
    salesByPerson: {
      salesperson: 'איש מכירות',
      dealCount: 'מס\' עסקאות',
      totalAmount: 'סה"כ (₪)',
    },
    installationsPending: {
      customer: 'לקוח',
      machine: 'מכונה',
      serial: 'מספר סידורי',
      city: 'עיר',
      technician: 'טכנאי/ת',
      plannedDate: 'תאריך מתוכנן',
    },
    leadsArchivedMeeting: {
      name: 'שם',
      phone: 'טלפון',
      city: 'עיר',
      notes: 'הערות',
    },
  },

  users: {
    title: 'משתמשים',
    addUser: 'הוספת משתמש',
    editUser: 'עריכת משתמש',
    role: 'תפקיד',
    userName: 'שם משתמש',
    isActive: 'פעיל',
    lastLogin: 'התחברות אחרונה',
    linkSalesPerson: 'קישור לאיש מכירות',
    reportPermissions: 'הרשאות לדוחות',
    setPassword: 'קביעת סיסמה',
    newPassword: 'סיסמה חדשה',
    revokeSessions: 'ביטול כל ההתחברויות',
    revokeSessionsConfirm: 'האם לבטל את כל ההתחברויות הפעילות של משתמש זה?',
    neverLoggedIn: 'מעולם לא התחבר',
  },

  role: {
    admin: 'מנהל ראשי',
    sales: 'מכירות',
    technician: 'טכנאי/ת',
  },

  notFound: {
    title: 'הדף לא נמצא',
    message: 'העמוד שחיפשת אינו קיים',
    backHome: 'חזרה לדף הבית',
  },
} as const
